site_name: ManaStack
site_url: http://manastack.com/
theme: readthedocs
pages:
- ['index.md', 'Introduction']
- ['cards.md', 'Cards']
- ['decks.md', 'Decks']
- ['sets.md', 'Sets']
- ['compute.md', 'Compute']
- ['simulation.md', 'Simulation']
- ['issues.md', 'Known Issues']
