site_name: ManaStack
site_url: http://manastack.com/
theme: readthedocs
pages:
    - Introduction: 'index.md'
    - ManaStack API: 
        - 'Cards': 'cards.md'
        - 'Decks': 'decks.md'
        - 'Sets' : 'sets.md'
        - 'Users' : 'users.md'
    - Compute Engine:
        - 'Introduction': 'compute.md'
        - 'Simulation': 'simulation.md'
        - 'Rules Support' : 'rules.md'
        - 'Known Issues': 'issues.md'